config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

   devise_for :users
   namespace :admin do
     resources :products
     resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
     end

   resources :products do
     member do
       post :add_to_cart
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items

   resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end


   namespace :account do
      resources :orders
   end

end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

   belongs_to :user

   validates :billing_name, presence: true
   validates :billing_address, presence: true
   validates :shipping_name, presence: true
   validates :shipping_address, presence: true
   has_many :product_lists

   def set_payment_with!(method)
     self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

   include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!

   def index
     @orders = current_user.orders.order("id DESC")
   end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @orders = Order.order("id DESC")
  end

   def show
     @order = Order.find(params[:id])
     @product_lists = @order.product_lists
   end

   def ship
    @order = Order.find(params[:id])
    @order.ship!
    OrderMailer.notify_ship(@order).deliver!
    redirect_to :back
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancel_order!
    OrderMailer.notify_ship(@order).deliver!
    redirect_to :back
  end

  def return
    @order = Order.find(params[:id])
    @order.return_good!
    redirect_to :back
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   before_action :authenticate_user!, only: [:create]

   def create
     @order = Order.new(order_params)
     @order.user = current_user
     @order.total = current_cart.total_price

     if @order.save

         current_cart.cart_items.each do |cart_item|
         product_list = ProductList.new
         product_list.order = @order
         product_list.product_name = cart_item.product.title
         product_list.product_price = cart_item.product.price
         product_list.quantity = cart_item.quantity
         product_list.save
       end

       current_cart.clean!
       OrderMailer.notify_order_placed(@order).deliver!

       redirect_to order_path(@order.token)
     else
       render 'carts/checkout'
     end
   end

   def show
     @order = Order.find_by_token(params[:id])
     @product_lists = @order.product_lists
   end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_to :back
  end

   private

   def order_params
     params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
   end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
   def render_order_paid_state(order)
     if order.is_paid?
       "已付款"
     else
       "未付款"
     end
   end
end

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">

    <h2> 订单明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
        </tr>
      </thead>
      <tbody>

        <% @product_lists.each do |product_list| %>
          <tr>
            <td>
              <%= product_list.product_name %>
            </td>
            <td>
              <%= product_list.product_price %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= @order.total %> CNY
      </span>
    </div>

     <hr>

     <h2> 寄送资讯 </h2>

     <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>
            订购人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order.billing_name %> - <%= @order.billing_address %>
          </td>
        </tr>
        <tr>
          <td>
            收件人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order.shipping_name %> - <%= @order.shipping_address %>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="pull-left">
      <% if @order.order_placed? || @order.paid? %>
        <%= link_to("申请取消订单", apply_to_cancel_order_path(@order), method: :post, class: "btn  btn-info") %>
      <% end %>
    </div>

    <% if !@order.is_paid? %>
    <div class="group pull-right">
      <%= link_to("以支付宝支付", pay_with_alipay_order_path(@order.token), :method => :post, :class => "btn btn-danger") %>
      <%= link_to("以微信支付", pay_with_wechat_order_path(@order.token), :method => :post, :class => "btn btn-danger") %>
    </div>
    <% else %>
      <p class="text-center">此订单已完成付款</p>
    <% end %>
  </div>
</div>