config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

   devise_for :users
   namespace :admin do
     resources :products
     resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
     end

   resources :products do
     member do
       post :add_to_cart
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items

   resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end


   namespace :account do
      resources :orders
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

def total_price
  sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum = sum + cart_item.quantity * cart_item.product.price
      end
    end
     sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

   belongs_to :user

   validates :billing_name, presence: true
   validates :billing_address, presence: true
   validates :shipping_name, presence: true
   validates :shipping_address, presence: true
   has_many :product_lists

   def set_payment_with!(method)
     self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

   include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
   belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def admin?
           is_admin
         end
   has_many :orders
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end

    helper_method :current_cart

    def current_cart
      @current_cart ||= find_cart
    end

    private

    def find_cart
      cart = Cart.find_by(id: session[:cart_id])
      if cart.blank?
        cart = Cart.create
      end
      session[:cart_id] = cart.id
      return cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!


     def update
       @cart = current_cart
       @cart_item = @cart.cart_items.find_by(product_id: params[:id])
        if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
          @cart_item.update(cart_item_params)
          flash[:notice] = "成功变更数量"
        else
          flash[:warning] = "数量不足以加入购物车"
        end

       redirect_to carts_path
     end


  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
    redirect_to :back
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def clean
   current_cart.clean!
   flash[:warning] = "已清空购物车"
   redirect_to carts_path
 end

   def checkout
     @order = Order.new
   end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   before_action :authenticate_user!, only: [:create]

   def create
     @order = Order.new(order_params)
     @order.user = current_user
     @order.total = current_cart.total_price

     if @order.save

         current_cart.cart_items.each do |cart_item|
         product_list = ProductList.new
         product_list.order = @order
         product_list.product_name = cart_item.product.title
         product_list.product_price = cart_item.product.price
         product_list.quantity = cart_item.quantity
         product_list.save
       end

       current_cart.clean!
       OrderMailer.notify_order_placed(@order).deliver!

       redirect_to order_path(@order.token)
     else
       render 'carts/checkout'
     end
   end

   def show
     @order = Order.find_by_token(params[:id])
     @product_lists = @order.product_lists
   end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_to :back
  end

   private

   def order_params
     params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)

       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
def render_cart_total_price(cart)
     cart.total_price
   end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
   def render_order_paid_state(order)
     if order.is_paid?
       "已付款"
     else
       "未付款"
     end
   end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-12">

    <h2> 购物明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>

            <td>
              <%= cart_item.quantity %>
            </td>

          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= render_cart_total_price(current_cart) %> CNY
      </span>
    </div>

    <hr>

    <h2> 订单资讯 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>



          <legend> 订购人</legend>
          <div class="form-group col-lg-6">
            <%= f.input :billing_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :billing_address  %>
          </div>

          <legend> 收货人</legend>
          <div class="form-group col-lg-6">
           <%= f.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :shipping_address  %>
          </div>

        <div class="checkout">
          <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">

      <%= link_to("清空购物车", clean_carts_path ,
              method: :delete , class: "pull-right",
              style: "text-decoration: underline;",
              data: { confirm: "你确定要清空整个购物车吗？"} )%>

    <h2> 购物车 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品资讯</th>
          <th>单价</th>
          <th>数量</th>
          <th>操作选项 </th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to product_path(cart_item.product) do %>
                <% if cart_item.product.image.present? %>
                  <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>
            <td>
             <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
                <%= f.select :quantity, 1..cart_item.product.quantity %>
                <%= f.submit "更新", data: { disable_with: "Submiting..." } %>
             <% end %>
             </td>
            <td>
              <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
        <span>
           总计 <%= render_cart_total_price(current_cart) %> RMB
       </span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
        <%= link_to("确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>