config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

   devise_for :users
   namespace :admin do
     resources :products
     resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
     end

   resources :products do
     member do
       post :add_to_cart
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items

   resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end


   namespace :account do
      resources :orders
   end

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required


  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end



  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)

       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

 <% if @product.image.present? %>
    <span>目前商品图</span> <br>
    <%= image_tag(@product.image.thumb.url) %>
 <% end %>

 <div class="group">
    <%= f.input :image, as: :file %>
 </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>