config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

   devise_for :users
   namespace :admin do
     resources :products
     resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
     end

   resources :products do
     member do
       post :add_to_cart
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items

   resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end


   namespace :account do
      resources :orders
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

def total_price
  sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum = sum + cart_item.quantity * cart_item.product.price
      end
    end
     sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

   belongs_to :user

   validates :billing_name, presence: true
   validates :billing_address, presence: true
   validates :shipping_name, presence: true
   validates :shipping_address, presence: true
   has_many :product_lists

   def set_payment_with!(method)
     self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

   include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
   belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def admin?
           is_admin
         end
   has_many :orders
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end

    helper_method :current_cart

    def current_cart
      @current_cart ||= find_cart
    end

    private

    def find_cart
      cart = Cart.find_by(id: session[:cart_id])
      if cart.blank?
        cart = Cart.create
      end
      session[:cart_id] = cart.id
      return cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!


     def update
       @cart = current_cart
       @cart_item = @cart.cart_items.find_by(product_id: params[:id])
        if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
          @cart_item.update(cart_item_params)
          flash[:notice] = "成功变更数量"
        else
          flash[:warning] = "数量不足以加入购物车"
        end

       redirect_to carts_path
     end


  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
    redirect_to :back
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def clean
   current_cart.clean!
   flash[:warning] = "已清空购物车"
   redirect_to carts_path
 end

   def checkout
     @order = Order.new
   end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   before_action :authenticate_user!, only: [:create]

   def create
     @order = Order.new(order_params)
     @order.user = current_user
     @order.total = current_cart.total_price

     if @order.save

         current_cart.cart_items.each do |cart_item|
         product_list = ProductList.new
         product_list.order = @order
         product_list.product_name = cart_item.product.title
         product_list.product_price = cart_item.product.price
         product_list.quantity = cart_item.quantity
         product_list.save
       end

       current_cart.clean!
       OrderMailer.notify_order_placed(@order).deliver!

       redirect_to order_path(@order.token)
     else
       render 'carts/checkout'
     end
   end

   def show
     @order = Order.find_by_token(params[:id])
     @product_lists = @order.product_lists
   end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_to :back
  end

   private

   def order_params
     params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)

       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
def render_cart_total_price(cart)
     cart.total_price
   end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
   def render_order_paid_state(order)
     if order.is_paid?
       "已付款"
     else
       "未付款"
     end
   end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 JDStore
        <br>Design by yourname

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">卖萌网 </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active">
                <%= link_to("Products", products_path) %>
            </li>
         </ul>
            <ul class="nav navbar-nav navbar-right">
               <li>
                  <%= link_to carts_path do  %>

                     购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
                  <% end %>
               </li>

              <% if !current_user %>
                    <li><%= link_to("注册", new_user_registration_path) %> </li>
                    <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
              <% else %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Hi!, <%= current_user.email %>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <% if current_user.admin? %>
                           <li>
                               <%= link_to("Admin 选单", admin_products_path ) %>
                           </li>
                       <% end %>
                       <li>
                         <%= link_to("个人订单列表", account_orders_path ) %>
                       </li>
                          <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                      </ul>
                    </li>
              <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jdstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="container-fluid">
          <div class="row">
            <%= render "common/navbar" %>
          </div>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>